// <auto-generated />
using System;
using Entities.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(PersonsDbContext))]
    [Migration("20251229183810_add_get_all_persons_stored_procedure")]
    partial class add_get_all_persons_stored_procedure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1e1f1d0-1111-4a2b-8888-123456789001"),
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("b2e2f2d0-2222-4b3c-9999-123456789002"),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("c3e3f3d0-3333-4c4d-aaaa-123456789003"),
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("d4e4f4d0-4444-4d5e-bbbb-123456789004"),
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("e5e5f5d0-5555-4e6f-cccc-123456789005"),
                            Name = "Brazil"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Gender")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("ReceiveNewsLetter")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-aaaa-4aaa-aaaa-111111111111"),
                            Address = "Cairo, Egypt",
                            CountryId = new Guid("a1e1f1d0-1111-4a2b-8888-123456789001"),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed.ali@example.com",
                            Gender = "Male",
                            Name = "Ahmed Ali",
                            ReceiveNewsLetter = true
                        },
                        new
                        {
                            Id = new Guid("11111112-aaaa-4aaa-aaaa-111111111112"),
                            Address = "Berlin, Germany",
                            CountryId = new Guid("b2e2f2d0-2222-4b3c-9999-123456789002"),
                            DateOfBirth = new DateTime(1985, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.hassan@example.com",
                            Gender = "Female",
                            Name = "Sara Hassan",
                            ReceiveNewsLetter = false
                        },
                        new
                        {
                            Id = new Guid("11111113-aaaa-4aaa-aaaa-111111111113"),
                            Address = "Paris, France",
                            CountryId = new Guid("c3e3f3d0-3333-4c4d-aaaa-123456789003"),
                            DateOfBirth = new DateTime(1992, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.smith@example.com",
                            Gender = "Male",
                            Name = "John Smith",
                            ReceiveNewsLetter = true
                        },
                        new
                        {
                            Id = new Guid("11111114-aaaa-4aaa-aaaa-111111111114"),
                            Address = "Tokyo, Japan",
                            CountryId = new Guid("d4e4f4d0-4444-4d5e-bbbb-123456789004"),
                            DateOfBirth = new DateTime(1995, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yuki.tanaka@example.com",
                            Gender = "Female",
                            Name = "Yuki Tanaka",
                            ReceiveNewsLetter = true
                        },
                        new
                        {
                            Id = new Guid("11111115-aaaa-4aaa-aaaa-111111111115"),
                            Address = "Rio de Janeiro, Brazil",
                            CountryId = new Guid("e5e5f5d0-5555-4e6f-cccc-123456789005"),
                            DateOfBirth = new DateTime(1988, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carlos.silva@example.com",
                            Gender = "Male",
                            Name = "Carlos Silva",
                            ReceiveNewsLetter = false
                        },
                        new
                        {
                            Id = new Guid("11111116-aaaa-4aaa-aaaa-111111111116"),
                            Address = "Alexandria, Egypt",
                            CountryId = new Guid("a1e1f1d0-1111-4a2b-8888-123456789001"),
                            DateOfBirth = new DateTime(1993, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laila.mohamed@example.com",
                            Gender = "Female",
                            Name = "Laila Mohamed",
                            ReceiveNewsLetter = true
                        },
                        new
                        {
                            Id = new Guid("11111117-aaaa-4aaa-aaaa-111111111117"),
                            Address = "Munich, Germany",
                            CountryId = new Guid("b2e2f2d0-2222-4b3c-9999-123456789002"),
                            DateOfBirth = new DateTime(1991, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thomas.muller@example.com",
                            Gender = "Male",
                            Name = "Thomas MUller",
                            ReceiveNewsLetter = false
                        },
                        new
                        {
                            Id = new Guid("11111118-aaaa-4aaa-aaaa-111111111118"),
                            Address = "Lyon, France",
                            CountryId = new Guid("c3e3f3d0-3333-4c4d-aaaa-123456789003"),
                            DateOfBirth = new DateTime(1990, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marie.dubois@example.com",
                            Gender = "Female",
                            Name = "Marie Dubois",
                            ReceiveNewsLetter = true
                        },
                        new
                        {
                            Id = new Guid("11111119-aaaa-4aaa-aaaa-111111111119"),
                            Address = "Osaka, Japan",
                            CountryId = new Guid("d4e4f4d0-4444-4d5e-bbbb-123456789004"),
                            DateOfBirth = new DateTime(1994, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kenji.sato@example.com",
                            Gender = "Male",
                            Name = "Kenji Sato",
                            ReceiveNewsLetter = true
                        },
                        new
                        {
                            Id = new Guid("11111120-aaaa-4aaa-aaaa-111111111120"),
                            Address = "SUo Paulo, Brazil",
                            CountryId = new Guid("e5e5f5d0-5555-4e6f-cccc-123456789005"),
                            DateOfBirth = new DateTime(1989, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana.pereira@example.com",
                            Gender = "Female",
                            Name = "Ana Pereira",
                            ReceiveNewsLetter = false
                        },
                        new
                        {
                            Id = new Guid("11111121-aaaa-4aaa-aaaa-111111111121"),
                            Address = "Giza, Egypt",
                            CountryId = new Guid("a1e1f1d0-1111-4a2b-8888-123456789001"),
                            DateOfBirth = new DateTime(1992, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mohamed.hassan@example.com",
                            Gender = "Male",
                            Name = "Mohamed Hassan",
                            ReceiveNewsLetter = true
                        },
                        new
                        {
                            Id = new Guid("11111122-aaaa-4aaa-aaaa-111111111122"),
                            Address = "Hamburg, Germany",
                            CountryId = new Guid("b2e2f2d0-2222-4b3c-9999-123456789002"),
                            DateOfBirth = new DateTime(1987, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "julia.schmidt@example.com",
                            Gender = "Female",
                            Name = "Julia Schmidt",
                            ReceiveNewsLetter = false
                        },
                        new
                        {
                            Id = new Guid("11111123-aaaa-4aaa-aaaa-111111111123"),
                            Address = "Marseille, France",
                            CountryId = new Guid("c3e3f3d0-3333-4c4d-aaaa-123456789003"),
                            DateOfBirth = new DateTime(1991, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pierre.martin@example.com",
                            Gender = "Male",
                            Name = "Pierre Martin",
                            ReceiveNewsLetter = true
                        },
                        new
                        {
                            Id = new Guid("11111124-aaaa-4aaa-aaaa-111111111124"),
                            Address = "Kyoto, Japan",
                            CountryId = new Guid("d4e4f4d0-4444-4d5e-bbbb-123456789004"),
                            DateOfBirth = new DateTime(1993, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hiroko.nakamura@example.com",
                            Gender = "Female",
                            Name = "Hiroko Nakamura",
                            ReceiveNewsLetter = true
                        },
                        new
                        {
                            Id = new Guid("11111125-aaaa-4aaa-aaaa-111111111125"),
                            Address = "BrasUlia, Brazil",
                            CountryId = new Guid("e5e5f5d0-5555-4e6f-cccc-123456789005"),
                            DateOfBirth = new DateTime(1990, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "felipe.costa@example.com",
                            Gender = "Male",
                            Name = "Felipe Costa",
                            ReceiveNewsLetter = false
                        },
                        new
                        {
                            Id = new Guid("11111126-aaaa-4aaa-aaaa-111111111126"),
                            Address = "Aswan, Egypt",
                            CountryId = new Guid("a1e1f1d0-1111-4a2b-8888-123456789001"),
                            DateOfBirth = new DateTime(1995, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nour.ahmed@example.com",
                            Gender = "Female",
                            Name = "Nour Ahmed",
                            ReceiveNewsLetter = true
                        },
                        new
                        {
                            Id = new Guid("11111127-aaaa-4aaa-aaaa-111111111127"),
                            Address = "Frankfurt, Germany",
                            CountryId = new Guid("b2e2f2d0-2222-4b3c-9999-123456789002"),
                            DateOfBirth = new DateTime(1988, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "markus.lehmann@example.com",
                            Gender = "Male",
                            Name = "Markus Lehmann",
                            ReceiveNewsLetter = false
                        },
                        new
                        {
                            Id = new Guid("11111128-aaaa-4aaa-aaaa-111111111128"),
                            Address = "Nice, France",
                            CountryId = new Guid("c3e3f3d0-3333-4c4d-aaaa-123456789003"),
                            DateOfBirth = new DateTime(1992, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "claire.moreau@example.com",
                            Gender = "Female",
                            Name = "Claire Moreau",
                            ReceiveNewsLetter = true
                        },
                        new
                        {
                            Id = new Guid("11111129-aaaa-4aaa-aaaa-111111111129"),
                            Address = "Hiroshima, Japan",
                            CountryId = new Guid("d4e4f4d0-4444-4d5e-bbbb-123456789004"),
                            DateOfBirth = new DateTime(1994, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "takashi.yamamoto@example.com",
                            Gender = "Male",
                            Name = "Takashi Yamamoto",
                            ReceiveNewsLetter = true
                        },
                        new
                        {
                            Id = new Guid("11111130-aaaa-4aaa-aaaa-111111111130"),
                            Address = "Salvador, Brazil",
                            CountryId = new Guid("e5e5f5d0-5555-4e6f-cccc-123456789005"),
                            DateOfBirth = new DateTime(1989, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "juliana.lima@example.com",
                            Gender = "Female",
                            Name = "Juliana Lima",
                            ReceiveNewsLetter = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
