// <auto-generated />
using System;
using CitiesManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitiesManager.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260112194347_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitiesManager.Models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("47c10b7d-1fab-4cf0-81fc-366ac8e17652"),
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("696d908c-957c-44f4-8098-19bd0eab4dc1"),
                            Name = "Manchester"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
